[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
remappings = ['@aave/core-v3/=lib/protocol-v3',
            '@openzeppelin=lib/openzeppelin-contracts',
            '@api3/contracts=lib/contracts/contracts',
            '@uniswap/v3-periphery=node_modules/@uniswap/v3-periphery',
            '@uniswap/v3-core=node_modules/@uniswap/v3-core',
            '@chainlink/contracts=lib/chainlink-brownie-contracts/contracts',
    ]

[Invariant]
runs = 128
depth = 128
fail_on_revert = true




# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
